name: Server Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build
            args: --package server --release
          - command: fmt
            args: --all -- --check --color always
          - command: clippy
            args:
              --package server --all-targets --all-features -- -W
              clippy::pedantic -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "server-build"
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
